# -----------------------------------------------------------------------------
# __________  ________
# \______   \/  _____/     .__
#  |       _/   \  ___   __|  |___
#  |    |   \    \_\  \ /__    __/
#  |____|_  /\______  /    |__|
#         \/        \/
# |
# SETTINGS.YML - This is where you configure the settings for RankGrant+.
# Support: https://demeng.dev/discord
# -----------------------------------------------------------------------------

config-version: 6

# The commands that will be executed on grant activation and expiration.
# These should correspond to your permission plugin and automatically set on startup.
# Do not include the /. Use %target% for the player name and %rank% for the rank ID.
commands:
  # The list of commands to be executed when a rank is granted.
  activation: [ ]
  # The list of commands to be executed when a rank expires.
  expiration: [ ]

# Style configuration for the menus.
menus:
  # Configuration for the rank selection menu.
  rank-select:
    # The number of slots in the menu.
    # Must be between 9 and 54 and be a multiple of 9.
    size: 54
    # The GUI title. You can use %target% for the target player's name.
    title: "Select a Rank"
  # Configuration for the duration selection menu.
  duration-select:
    size: 54
    title: "Select a Duration"
    # The button for adding 1 minute to the duration.
    add-minute:
      # The slot that this button should go in, starts at 1.
      slot: 12
      # The name of the material for the button.
      material: "EMERALD_BLOCK"
      # The display name of the button.
      display-name: "&a+1 Minute"
      # The lore of the button.
      # You can use %duration% for the current duration.
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 hour to the duration.
    add-hour:
      slot: 21
      material: "EMERALD_BLOCK"
      display-name: "&a+1 Hour"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 day to the duration.
    add-day:
      slot: 30
      material: "EMERALD_BLOCK"
      display-name: "&a+1 Day"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 week to the duration.
    add-week:
      slot: 39
      material: "EMERALD_BLOCK"
      display-name: "&a+1 Week"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for subtracting 1 minute to the duration.
    subtract-minute:
      slot: 16
      material: "REDSTONE_BLOCK"
      display-name: "&c-1 Minute"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 hour to the duration.
    subtract-hour:
      slot: 25
      material: "REDSTONE_BLOCK"
      display-name: "&c-1 Hour"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 day to the duration.
    subtract-day:
      slot: 34
      material: "REDSTONE_BLOCK"
      display-name: "&c-1 Day"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 week to the duration.
    subtract-week:
      slot: 43
      material: "REDSTONE_BLOCK"
      display-name: "&c-1 Week"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button to continue to reason selection.
    continue:
      slot: 54
      material: "ARROW"
      display-name: "&6&lContinue"
      lore:
        - "&eClick to confirm the grant duration of &f%duration%&e."
  # Configuration for the reason selection menu.
  reason-select:
    size: 54
    title: "Select a Reason"
