# -----------------------------------------------------------------------------
# __________  ________
# \______   \/  _____/     .__
#  |       _/   \  ___   __|  |___
#  |    |   \    \_\  \ /__    __/
#  |____|_  /\______  /    |__|
#         \/        \/
# |
# SETTINGS.YML - This is where you configure the settings for RankGrant+.
# Support: https://demeng.dev/discord
# -----------------------------------------------------------------------------

config-version: 7

# The commands that will be executed on grant activation and expiration.
# These should correspond to your permission plugin and automatically set on startup.
# Do not include the /. Use %target% for the player name and %rank% for the rank ID.
commands:
  # The list of commands to be executed when a rank is granted.
  activation: [ ]
  # The list of commands to be executed when a rank expires.
  expiration: [ ]

# Style configuration for the menus.
menus:
  # Configuration for the rank selection menu.
  rank-select:
    # The number of slots in the menu.
    # Must be between 9 and 54 and be a multiple of 9.
    size: 54
    # The GUI title. You can use %target% for the target player's name.
    title: "Select a Rank"
  # Configuration for the duration selection menu.
  duration-select:
    size: 54
    title: "Select a Duration"
    # The button for adding 1 minute to the duration.
    add-minute:
      # The slot that this button should go in, starts at 1.
      slot: 12
      # The name of the material for the button.
      material: "EMERALD_BLOCK"
      # The display name of the button.
      name: "&a+1 Minute"
      # The lore of the button.
      # You can use %duration% for the current duration.
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 hour to the duration.
    add-hour:
      slot: 21
      material: "EMERALD_BLOCK"
      name: "&a+1 Hour"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 day to the duration.
    add-day:
      slot: 30
      material: "EMERALD_BLOCK"
      name: "&a+1 Day"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for adding 1 week to the duration.
    add-week:
      slot: 39
      material: "EMERALD_BLOCK"
      name: "&a+1 Week"
      lore:
        - "&aCurrent Duration: &f%duration%"
    # The button for subtracting 1 minute to the duration.
    subtract-minute:
      slot: 16
      material: "REDSTONE_BLOCK"
      name: "&c-1 Minute"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 hour to the duration.
    subtract-hour:
      slot: 25
      material: "REDSTONE_BLOCK"
      name: "&c-1 Hour"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 day to the duration.
    subtract-day:
      slot: 34
      material: "REDSTONE_BLOCK"
      name: "&c-1 Day"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button for subtracting 1 week to the duration.
    subtract-week:
      slot: 43
      material: "REDSTONE_BLOCK"
      name: "&c-1 Week"
      lore:
        - "&cCurrent Duration: &f%duration%"
    # The button to continue to reason selection.
    continue:
      slot: 54
      material: "ARROW"
      name: "&6&lContinue"
      lore:
        - "&eClick to confirm the grant duration of &f%duration%&e."
  # Configuration for the reason selection menu.
  reason-select:
    size: 36
    title: "Select a Reason"
    # The list of reasons that will be available for selection.
    reasons:
      # The reason ID (can be anything).
      issue:
        slot: 1
        material: "PAPER"
        # The display name- will be used in both the GUI and chat messages.
        name: "&aDonation Store Issues"
        lore:
          - "&fThere was an issue in the donation store."
        # The custom permission node required to choose this reason.
        permission: "none"
      promotion:
        slot: 2
        material: "PAPER"
        name: "&aPromotion"
        lore:
          - "&fPromote %target% to the %rank% rank!"
        permission: "none"
      demotion:
        slot: 3
        material: "PAPER"
        name: "&aDemotion"
        lore:
          - "&fDemote %target% to the %rank% rank!"
        permission: "none"
      other:
        slot: 4
        material: "BOOK"
        name: "&aOther"
        lore:
          - "&fThis grant has no reason or the reason is not listed."
        permission: "none"
  # Configuration for the grant confirmation menu.
  confirm:
    size: 27
    title: "Confirm Grant"
    # The button for confirming the grant.
    # %target% - The name of the player receiving the rank.
    # %rank% - The rank to be given.
    # %duration% - The duration of the grant.
    # %reason% - The reason of the grant.
    confirm:
      slot: 12
      material: "GREEN_TERRACOTTA"
      name: "&2Confirm Grant"
      lore:
        - "&aTarget: &f%target%"
        - "&aRank: &f%rank%"
        - "&aDuration: &f%duration%"
        - "&aReason: &f%reason%"
    # The button for cancelling the grant.
    cancel:
      slot: 16
      material: "RED_TERRACOTTA"
      name: "&4Cancel Grant"
      lore:
        - "&cTarget: &f%target%"
        - "&cRank: &f%rank%"
        - "&cDuration: &f%duration%"
        - "&cReason: &f%reason%"
