# -----------------------------------------------------------------------------
# __________  ________
# \______   \/  _____/     .__
#  |       _/   \  ___   __|  |___
#  |    |   \    \_\  \ /__    __/
#  |____|_  /\______  /    |__|
#         \/        \/
# |
# SETTINGS.YML - This is where you configure the settings for RankGrant+.
# Support: https://demeng.dev/discord
# -----------------------------------------------------------------------------

config-version: 6

# The commands that will be executed on grant activation and expiration.
# These should correspond to your permission plugin and automatically set on startup.
# Do not include the /. Use %target% for the player name and %rank% for the rank ID.
commands:
  # The list of commands to be executed when a rank is granted.
  activation: [ ]
  # The list of commands to be executed when a rank expires.
  expiration: [ ]

# Style configuration for the menus.
menus:
  # Configuration for the rank selection menu.
  rank-select:
    # The number of slots in the menu.
    # Must be between 9 and 54 and be a multiple of 9.
    slots: 54
    # The GUI title. You can use %target% for the target player's name.
    title: "Select a Rank"
